/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bmi;

import java.awt.im.InputContext;
import java.util.Locale;
import javax.swing.JFrame;



/**
 *
 * @author Dineth
 */
public class Calc extends javax.swing.JFrame {
        InputContext data=InputContext.getInstance();
       Locale region= data.getLocale();
       static float bmi_value=(float) 4.123;
   
    public Calc() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSlider1 = new javax.swing.JSlider();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        lblResult = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        chkRegion = new javax.swing.JCheckBox();
        lblRegion = new javax.swing.JLabel();
        txtHeight = new javax.swing.JTextField();
        txtWeight = new javax.swing.JTextField();
        lblMale = new javax.swing.JLabel();
        lblFemale = new javax.swing.JLabel();
        lblTransgender = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        lblCal = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 102, 102));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(new java.awt.Color(0, 204, 204));
        setMaximumSize(new java.awt.Dimension(800, 370));
        setMinimumSize(new java.awt.Dimension(800, 370));
        setName("BMI"); // NOI18N
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(800, 370));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
        });

        jPanel1.setMaximumSize(new java.awt.Dimension(800, 370));
        jPanel1.setMinimumSize(new java.awt.Dimension(800, 370));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 370));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(37, 38, 38,90));
        jPanel2.setForeground(new java.awt.Color(158, 13, 13));
        jPanel2.setOpaque(false);

        jPanel4.setBackground(new java.awt.Color(0, 0, 0,200));

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Name");

        txtName.setBackground(new java.awt.Color(0, 0, 0,150));
        txtName.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        txtName.setForeground(new java.awt.Color(255, 255, 255));
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        jTextField2.setBackground(new java.awt.Color(0, 0, 0,180));
        jTextField2.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(255, 255, 255));
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Name");

        jLabel6.setText("Region");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(0, 0, 0,200));

        lblResult.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lblResult.setForeground(new java.awt.Color(255, 255, 255));
        lblResult.setMaximumSize(new java.awt.Dimension(29, 21));
        lblResult.setMinimumSize(new java.awt.Dimension(29, 21));
        lblResult.setPreferredSize(new java.awt.Dimension(29, 21));

        jLabel9.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Your BMI Value is :");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblResult, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblResult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(20, 20, 20))
        );

        jPanel6.setBackground(new java.awt.Color(0, 0, 0,200));

        jLabel7.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Height");

        jLabel8.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Weight");

        chkRegion.setBackground(new java.awt.Color(0, 0, 0,200));
        chkRegion.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        chkRegion.setForeground(new java.awt.Color(255, 255, 255));
        chkRegion.setText("Beyond the Region");
        chkRegion.setToolTipText("");
        chkRegion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chkRegionMouseClicked(evt);
            }
        });
        chkRegion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkRegionActionPerformed(evt);
            }
        });

        lblRegion.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lblRegion.setForeground(new java.awt.Color(255, 255, 255));
        lblRegion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        txtHeight.setBackground(new java.awt.Color(0, 0, 0,150));
        txtHeight.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        txtHeight.setForeground(new java.awt.Color(255, 255, 255));
        txtHeight.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtHeightMouseClicked(evt);
            }
        });

        txtWeight.setBackground(new java.awt.Color(0, 0, 0,150));
        txtWeight.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        txtWeight.setForeground(new java.awt.Color(255, 255, 255));
        txtWeight.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtWeightMouseClicked(evt);
            }
        });

        lblMale.setBackground(new java.awt.Color(41, 41, 41));
        lblMale.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bmi/Image/icons8_male_50px.png"))); // NOI18N
        lblMale.setToolTipText("Male");
        lblMale.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblMaleMouseMoved(evt);
            }
        });
        lblMale.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMaleMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblMaleMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblMaleMouseExited(evt);
            }
        });

        lblFemale.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bmi/Image/icons8_female_50px.png"))); // NOI18N
        lblFemale.setToolTipText("Female");
        lblFemale.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFemaleMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblFemaleMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblFemaleMouseExited(evt);
            }
        });

        lblTransgender.setBackground(new java.awt.Color(41, 41, 41));
        lblTransgender.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bmi/Image/icons8_transgender_55px.png"))); // NOI18N
        lblTransgender.setToolTipText("Transgender");
        lblTransgender.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTransgenderMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblTransgenderMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblTransgenderMouseExited(evt);
            }
        });

        jPanel8.setBackground(new java.awt.Color(0, 0, 0));
        jPanel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel8MouseClicked(evt);
            }
        });

        lblCal.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        lblCal.setForeground(new java.awt.Color(255, 255, 255));
        lblCal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCal.setText("Calculate");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(99, Short.MAX_VALUE)
                .addComponent(lblCal, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCal, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bmi/Image/icons8-reset-35.png"))); // NOI18N
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkRegion)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel6Layout.createSequentialGroup()
                                            .addGap(60, 60, 60)
                                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel6Layout.createSequentialGroup()
                                                    .addComponent(jLabel7)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(txtHeight, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(jPanel6Layout.createSequentialGroup()
                                                    .addComponent(jLabel8)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(txtWeight, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGap(36, 36, 36))
                                        .addGroup(jPanel6Layout.createSequentialGroup()
                                            .addComponent(lblMale)
                                            .addGap(74, 74, 74)
                                            .addComponent(lblFemale, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGap(69, 69, 69)
                                            .addComponent(lblTransgender)))
                                    .addComponent(lblRegion, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(5, 5, 5)
                .addComponent(jLabel11)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkRegion)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblRegion, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtHeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtWeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMale, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblFemale, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTransgender, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        jPanel16.setBackground(new java.awt.Color(0, 0, 0,200));
        jPanel16.setMaximumSize(new java.awt.Dimension(191, 42));
        jPanel16.setMinimumSize(new java.awt.Dimension(191, 42));
        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(0, 0, 0,200));
        jPanel7.setForeground(new java.awt.Color(255, 255, 255));
        jPanel7.setPreferredSize(new java.awt.Dimension(390, 30));

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Underweight");
        jLabel10.setPreferredSize(null);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                    .addContainerGap(9, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(14, Short.MAX_VALUE)))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                    .addContainerGap(12, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(12, Short.MAX_VALUE)))
        );

        jPanel16.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 390, 40));

        jPanel10.setBackground(new java.awt.Color(0, 0, 0,200));
        jPanel10.setForeground(new java.awt.Color(255, 255, 255));

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Normal weight");
        jLabel13.setPreferredSize(null);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel16.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 390, 40));

        jPanel11.setBackground(new java.awt.Color(0, 0, 0,200));
        jPanel11.setForeground(new java.awt.Color(255, 255, 255));

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Pre-obesity");
        jLabel14.setPreferredSize(null);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel16.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 390, 40));

        jPanel12.setBackground(new java.awt.Color(0, 0, 0,200));
        jPanel12.setForeground(new java.awt.Color(255, 255, 255));

        jLabel15.setBackground(new java.awt.Color(0, 0, 0,200));
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Obesity class I  ");
        jLabel15.setPreferredSize(null);

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel16.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 390, 40));

        jPanel13.setBackground(new java.awt.Color(0, 0, 0,200));
        jPanel13.setForeground(new java.awt.Color(255, 255, 255));

        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Obesity class II  ");
        jLabel16.setPreferredSize(null);

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel16.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 390, 40));

        jPanel14.setBackground(new java.awt.Color(0, 0, 0,200));
        jPanel14.setForeground(new java.awt.Color(255, 255, 255));

        jLabel17.setBackground(new java.awt.Color(0, 0, 0,200));
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Obesity class III  ");
        jLabel17.setPreferredSize(null);

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel16.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 390, 40));

        jPanel18.setBackground(new java.awt.Color(204, 204, 0,200));
        jPanel18.setForeground(new java.awt.Color(255, 255, 255));
        jPanel18.setMaximumSize(new java.awt.Dimension(191, 42));
        jPanel18.setMinimumSize(new java.awt.Dimension(191, 42));

        jLabel22.setBackground(new java.awt.Color(153, 0, 0));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("<html>35.0–39.9  </html>");

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel18Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(3, 3, 3)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel16, javax.swing.GroupLayout.DEFAULT_SIZE, 393, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(3, 3, 3))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(297, 297, 297)
                .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 800, 340));

        jPanel3.setBackground(new java.awt.Color(0, 0,0,200));
        jPanel3.setMaximumSize(new java.awt.Dimension(800, 30));
        jPanel3.setMinimumSize(new java.awt.Dimension(800, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bmi/Image/icons8_close_window_30px.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bmi/Image/icons8_minimize_window_30px.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(250, 250, 250));
        jLabel12.setText("Body Mass Index");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 346, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(277, 277, 277)
                .addComponent(jLabel3)
                .addGap(0, 0, 0)
                .addComponent(jLabel2))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dineth\\Documents\\y2mate.com - no_copyright_copyright_free_videos_motion_graphics_movies_background_animation_clips_download_fCPEAq6FMF8_1080p.gif")); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 370));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void chkRegionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkRegionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkRegionActionPerformed

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered
        System.out.println(region);
    //   String country = region.getDisplayCountry();
    String value=lblRegion.getText();
        if ((region.equals("en_UK")) && (value.equals("")))
        lblRegion.setText("British Imperial System - BI");
        else if((!region.equals("en_UK")) && (value.equals("")))
            lblRegion.setText("Standerds of Internatonal Units -SI");
    }//GEN-LAST:event_formMouseEntered

    private void chkRegionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chkRegionMouseClicked
       
        
        if((chkRegion.isSelected()) && (!region.equals("en_UK"))){
               // txtHeight.setForeground(new java.awt.Color(0, 0, 0));
                txtHeight.setText("Centimeters");
               // txtWeight.setForeground(new java.awt.Color(0, 0, 0));
                txtWeight.setText("Kilograms");
                lblRegion.setText("British Imperial System - BI");
        }
        else if ((chkRegion.isSelected()) && (region.equals("en_UK"))){
               //txtHeight.setForeground(new java.awt.Color(0, 0, 0));
                txtHeight.setText("Inches");
              // txtWeight.setForeground(new java.awt.Color(0, 0, 0));
                txtWeight.setText("Pounds");
                lblRegion.setText("Standerds of Internatonal Units -SI");
        }
        else if  ((!chkRegion.isSelected()) && (region.equals("en_UK"))){
              // txtHeight.setForeground(new java.awt.Color(0, 0, 0));
                txtHeight.setText("Centimeters");
             //  txtWeight.setForeground(new java.awt.Color(0, 0, 0));
                txtWeight.setText("Kilograms");
                lblRegion.setText("British Imperial System - BI");
        }
        
         else if  ((!chkRegion.isSelected()) && (!region.equals("en_UK"))){
             //  txtHeight.setForeground(new java.awt.Color(0, 0, 0));
                txtHeight.setText("Inches");
             //  txtWeight.setForeground(new java.awt.Color(0, 0, 0));
                txtWeight.setText("Pounds");
                lblRegion.setText("Standerds of Internatonal Units -SI");
        }
    }//GEN-LAST:event_chkRegionMouseClicked

    private void txtHeightMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtHeightMouseClicked
        String val_height=txtHeight.getText();
        if ((val_height.equals("Centimeters")) ||(val_height.equals("Inches"))){
            txtHeight.setText("");
        }
    }//GEN-LAST:event_txtHeightMouseClicked

    private void txtWeightMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtWeightMouseClicked
                String val_weight=txtWeight.getText();
        if ((val_weight.equals("Kilograms")) ||(val_weight.equals("Pounds"))){
            txtWeight.setText("");
        }
    }//GEN-LAST:event_txtWeightMouseClicked
int click_count=1;
    private void lblMaleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMaleMouseClicked
    lblMale.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bmi/Image/icons8_male_50px_1.png")));
    lblFemale.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bmi/Image/icons8_female_50px.png")));
    lblTransgender.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bmi/Image/icons8_transgender_55px.png"))); // NOI18N

    click_count=2;
    
    
    }//GEN-LAST:event_lblMaleMouseClicked
    public float tempM(float bmi1) {
       bmi_value=bmi1;
        System.out.println("hii "+this.bmi_value);
        return bmi_value;
    }
    private void lblMaleMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMaleMouseEntered
        lblMale.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bmi/Image/icons8_male_50px_1.png")));
    }//GEN-LAST:event_lblMaleMouseEntered

    private void lblMaleMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMaleMouseExited
        if (click_count!=2)
        lblMale.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bmi/Image/icons8_male_50px.png")));
    }//GEN-LAST:event_lblMaleMouseExited

    private void lblMaleMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMaleMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_lblMaleMouseMoved

    private void lblFemaleMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFemaleMouseEntered
        lblFemale.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bmi/Image/icons8_female_50px_1.png"))); // NOI18N
    }//GEN-LAST:event_lblFemaleMouseEntered

    private void lblFemaleMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFemaleMouseExited
      if (click_count!=3) 
        lblFemale.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bmi/Image/icons8_female_50px.png"))); // NOI18N

    }//GEN-LAST:event_lblFemaleMouseExited

    private void lblFemaleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFemaleMouseClicked
        
        click_count=3;
        lblFemale.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bmi/Image/icons8_female_50px_1.png"))); 
        lblMale.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bmi/Image/icons8_male_50px.png")));// NOI18N
        lblTransgender.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bmi/Image/icons8_transgender_55px.png"))); // NOI18N
        // TODO add your handling code here:
        
        ///444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444
        
        
        
        
        
        
        
        
        
        
        
        
        ////######################################################################################################3
        
        
        
    }//GEN-LAST:event_lblFemaleMouseClicked

    private void lblTransgenderMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTransgenderMouseEntered
        lblTransgender.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bmi/Image/icons8_transgender_55px_2.png"))); // NOI18N

    }//GEN-LAST:event_lblTransgenderMouseEntered

    private void lblTransgenderMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTransgenderMouseExited
      if(click_count!=4)
        lblTransgender.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bmi/Image/icons8_transgender_55px.png"))); // NOI18N

    }//GEN-LAST:event_lblTransgenderMouseExited

    private void lblTransgenderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTransgenderMouseClicked
       
        click_count=4;
        lblTransgender.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bmi/Image/icons8_transgender_55px_2.png"))); // NOI18N
        lblMale.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bmi/Image/icons8_male_50px.png")));
        lblFemale.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bmi/Image/icons8_female_50px.png"))); 
        

// TODO add your handling code here:
    }//GEN-LAST:event_lblTransgenderMouseClicked

    private void jPanel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel8MouseClicked
        GetSet c=new GetSet();
        try {
            String temp=txtHeight.getText();
            int height=Integer.parseInt(temp);
            c.compute(height);
            String temp1=txtWeight.getText();
            float weight=Float.valueOf(temp1);
            c.compute(weight);
            Boolean standerd=null;
             String status=lblRegion.getText();
            if (status.equals("Standerds of Internatonal Units -SI")){
                    standerd=true;
                    c.compute(standerd);
                    c.final_value();
                    System.out.println(c.pass());
            }
            txtName.setEditable(false);
            lblResult.setText(String.valueOf(bmi_value));
        } catch (Exception e) {
            System.out.println("Error ooi");
        }
            String range=lblResult.getText();
            float range2=Float.valueOf(range);
        if (range2<18.5){
            jPanel7.setBackground(new java.awt.Color(255, 0, 0,200));
        
            jPanel10.setBackground(new java.awt.Color(0, 0, 0,200));
            jPanel11.setBackground(new java.awt.Color(0, 0, 0,200));
            jPanel12.setBackground(new java.awt.Color(0, 0, 0,200));
            jPanel13.setBackground(new java.awt.Color(0, 0, 0,200));
            jPanel14.setBackground(new java.awt.Color(0, 0, 0,200));
        }
        else if (range2<25.0){
            jPanel10.setBackground(new java.awt.Color(0, 255, 40,200));
            
            jPanel7.setBackground(new java.awt.Color(0, 0, 0,200));
            jPanel11.setBackground(new java.awt.Color(0, 0, 0,200));
            jPanel12.setBackground(new java.awt.Color(0, 0, 0,200));
            jPanel13.setBackground(new java.awt.Color(0, 0, 0,200));
            jPanel14.setBackground(new java.awt.Color(0, 0, 0,200));
        }
        else if (range2<30.0){
            jPanel11.setBackground(new java.awt.Color(0, 230, 191,200));
            
            jPanel7.setBackground(new java.awt.Color(0, 0, 0,200));
            jPanel10.setBackground(new java.awt.Color(0, 0, 0,200));
            jPanel12.setBackground(new java.awt.Color(0, 0, 0,200));
            jPanel13.setBackground(new java.awt.Color(0, 0, 0,200));
            jPanel14.setBackground(new java.awt.Color(0, 0, 0,200));
        }
        else if (range2<35){
            jPanel12.setBackground(new java.awt.Color(0, 102, 204,200));
           
            jPanel7.setBackground(new java.awt.Color(0, 0, 0,200));
            jPanel11.setBackground(new java.awt.Color(0, 0, 0,200));
            jPanel10.setBackground(new java.awt.Color(0, 0, 0,200));
            jPanel13.setBackground(new java.awt.Color(0, 0, 0,200));
            jPanel14.setBackground(new java.awt.Color(0, 0, 0,200));
        }
        else if (range2<40){
            jPanel13.setBackground(new java.awt.Color(0, 0, 255,200));
            jPanel7.setBackground(new java.awt.Color(0, 0, 0,200));
            jPanel11.setBackground(new java.awt.Color(0, 0, 0,200));
            jPanel12.setBackground(new java.awt.Color(0, 0, 0,200));
            jPanel10.setBackground(new java.awt.Color(0, 0, 0,200));
            jPanel14.setBackground(new java.awt.Color(0, 0, 0,200)); 
            
        }
        else if (range2>40){
            jPanel14.setBackground(new java.awt.Color(128, 0, 128,200));

            jPanel7.setBackground(new java.awt.Color(0, 0, 0,200));
            jPanel11.setBackground(new java.awt.Color(0, 0, 0,200));
            jPanel12.setBackground(new java.awt.Color(0, 0, 0,200));
            jPanel13.setBackground(new java.awt.Color(0, 0, 0,200));
            jPanel10.setBackground(new java.awt.Color(0, 0, 0,200));
        }
            



    }//GEN-LAST:event_jPanel8MouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        txtName.setText("");
        chkRegion.setSelected(false);
        txtHeight.setText("");
        txtWeight.setText("");
        lblMale.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bmi/Image/icons8_male_50px.png")));
        lblFemale.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bmi/Image/icons8_female_50px.png"))); 
        lblTransgender.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bmi/Image/icons8_transgender_55px.png"))); 
        lblResult.setText("");
        jPanel7.setBackground(new java.awt.Color(0, 0, 0,200));
        jPanel11.setBackground(new java.awt.Color(0, 0, 0,200));
        jPanel12.setBackground(new java.awt.Color(0, 0, 0,200));
        jPanel13.setBackground(new java.awt.Color(0, 0, 0,200));
        jPanel10.setBackground(new java.awt.Color(0, 0, 0,200));
        jPanel14.setBackground(new java.awt.Color(0, 0, 0,200));
        txtName.setEditable(true);

    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
       System.exit(0);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        setState(JFrame.ICONIFIED);
            // TODO add your handling code here:
    }//GEN-LAST:event_jLabel3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox chkRegion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel lblCal;
    private javax.swing.JLabel lblFemale;
    private javax.swing.JLabel lblMale;
    private javax.swing.JLabel lblRegion;
    private javax.swing.JLabel lblResult;
    private javax.swing.JLabel lblTransgender;
    private javax.swing.JTextField txtHeight;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtWeight;
    // End of variables declaration//GEN-END:variables

    void tem(float bmi_val) {
        this.bmi_value=bmi_val;
    }


    
    
}
